### ISSUE TITLE
Readme niet up to date

### ISSUE THREAD

**Issue by ThEWiZ76** [mrWheel/DSMRlogger2HTTP#1]
https://github.com/mrWheel/DSMRlogger2HTTP/blob/master/bin/README.md

Naast dat hier nog de oude versie benoemd wordt van de firmware, klopt de omschrijving van de esptool ook niet meer. Als ik het commando probeer uit te voeren krijg ik `esptool: error: argument --chip/-c: invalid choice: 'd' (choose from 'auto', 'esp8266', 'esp32')`

nieuwe argumenten zijn:
```
usage: esptool [-h] [--chip {auto,esp8266,esp32}] [--port PORT] [--baud BAUD]
               [--before {default_reset,no_reset,no_reset_no_sync}]
               [--after {hard_reset,soft_reset,no_reset}] [--no-stub]
               [--trace] [--override-vddsdio [{1.8V,1.9V,OFF}]]
               {load_ram,dump_mem,read_mem,write_mem,write_flash,run,image_info,make_image,elf2image,read_mac,chip_id,flash_id,read_flash_status,write_flash_status,read_flash,verify_flash,erase_flash,erase_region,version}
```

**Comment by softstones** [comment]
Probleem met de nieuwere versie van esptool bestaat nog steeds, het commando werkt niet. Ik kan zo niet de SPIFFS flashen.

**Comment by mrWheel** [comment]
@softstones 
Ik gebruik gewoon de Arduino IDE om SPIFFS te flashen.
Maar blijkbaar moet je bij jouw versie niet "-cd nodemcu" maar "-chip esp8266" opgeven..
Mijn versie van de Arduino IDE (1.8.7) geeft precies het commando zoals in de readme staat.

**Comment by softstones** [comment]
Via de Arduino IDE lukt het niet om SPIFFS te flashen, want ik kan de knop 'ESP8266 Sketch Data Upload' onder 'Tools' niet vinden, ondanks dat ik het ESP8266FS.java bestand heb toegevoegd.

**Comment by mrWheel** [comment]
Hier staat hoe je dat kunt installeren:

https://willem.aandewiel.nl/index.php/2018/09/27/aan-de-slag-met-de-esp8266/2/ <https://willem.aandewiel.nl/index.php/2018/09/27/aan-de-slag-met-de-esp8266/2/>

Succes
Willem

gsm: 0653 - 499 551
www: http://www.aandewiel.nl/
---
At the source of every error which is blamed on the computer you will find at least two human errors, including the error of blaming it on the computer.

**Comment by mrWheel** [comment]
Hier staat hoe je dat kunt installeren:

https://willem.aandewiel.nl/index.php/2018/09/27/aan-de-slag-met-de-esp8266/2/

Succes
Willem

**Comment by softstones** [comment]
Bedankt. Ik had m'n comment al verwijderd, want het was al gelukt. Maar misschien nuttig voor anderen om te laten staan inderdaad.

**Comment by meer002** [comment]
Beste Mrwheel,
allereerst mij dank voor je werk. heb je smartmeter print ontwerp besteld incl esp en aan het vechten met de programmering ( via usb01 usb) en Sketc Arduino 1.8.8 met generik ESP8266 board ((black)
Ik krijg een declaration error op line 346 (dateTime=buildDateTimString(pTimestamp)
