### ISSUE TITLE
FileNotFound

### ISSUE THREAD

**Issue by bakman2** [mrWheel/DSMRlogger2HTTP#11]
Alles lijkt te werken, json, csv’s, telnet stream. 

Maar de index.html/js komt terug met FileNotFound

Ik heb de laatste versie van esp8266 geinstalleerd (2.5.0), upload werkt. 

Is dit een SPIFSS issue?

**Comment by bakman2** [comment]
Ok ik heb gevonden via je blog ergens op bladzijde 2. De instructies zouden iets efficienter kunnen. 
Ik wil het eventueel wel herschijven voor wiki vorm als je daar voor open staat @mrWheel

**Comment by mrWheel** [comment]
@bakman2 ,

Ik weet niet waar je problemen mee had. Waarschijnlijk de data map niet ge-upload? Blijkbaar staat het dus wel op mijn post maar is het moeilijk te vinden.
Als je wilt helpen alles duidelijk(er) te maken sta ik daar natuurlijk voor open. Dat is immers het idee van Open Source!

**Comment by jicho** [comment]
@mrWheel :
> Als je wilt helpen alles duidelijk(er) te maken sta ik daar natuurlijk voor open. Dat is immers het idee van Open Source!

Misschien handig om de Wiki te activeren voor dit project? Kan in de basis de huidige PDF handleiding hier neergezet worden in markdown (of restructured text) en hij is, volgens mij, dan ook makkelijk aan te vullen door derden.

Idee?

**Comment by mrWheel** [comment]
Hm....

Goed idee, maar ik moet even uitzoeken hoe dat moet.
Ga ik morgenmiddag mee aan de slag en kom daar bij je op terug.

Groet,

Willem 

gsm: 0653 - 499 551
www: http://willem.aandewiel.nl/


---
Thank God I'm Atheist

Verstuurd vanaf mijn iPad

**Comment by jicho** [comment]
Ben benieuwd of het lukt :)

Zou meteen een mooie zijn waar je FAQ's kwijt kunt!

**Comment by mrWheel** [comment]
Wat wil je dat ik er instop?
De bouwbeschrijving?
Of zet je er -in eerste instantie- zelf in wat je nodig hebt?

Keep me posted!

Groet,

Willem

gsm: 0653 - 499 551
www: http://www.aandewiel.nl/
---
Love -- the last of the serious diseases of childhood.

**Comment by bakman2** [comment]
Ik ben aan het schrijven, kort en bondig maar van A tot Z, in de hoop dat iedereen dit project kan maken :)

Mijn hobbels waren:
1) ESP01 flashen, dit niet vanzelfsprekend
2) SPIFFS, las er te snel/makkelijk overheen. 

Ik ben geen electronica guru dus heb graag wat guidelines, dingen spreken voor mij niet altijd voor zich.

**Comment by mrWheel** [comment]
Kun je mij een email adres geven?
Communiceert wat makkelijker.

Groet,

Willem

gsm: 0653 - 499 551
www: http://www.aandewiel.nl/
---
Time is but the stream I go a-fishing in. -- Henry David Thoreau

**Comment by bakman2** [comment]
Dat is op zich prima, maar ik wil 'm alleen niet hier neerzetten. :#

**Comment by mrWheel** [comment]
Zet dan even een comment op mijn website.
Ik haal het comment weer weg maar heb dan wel jou email adres!

Groet,

Willem

gsm: 0653 - 499 551
www: http://www.aandewiel.nl/
---
People who have what they want are very fond of telling people who haven't what they want that they don't want it. -- Ogden Nash

**Comment by jicho** [comment]
@mrWheel ik zou sowieso de bouwinstructie plaatsen, scheelt een PDF genereren en is makkelijk te onderhouden.

**Comment by bakman2** [comment]
Done @mrWheel
