### ISSUE TITLE
Telegramcounter is incremented twice

### ISSUE THREAD

**Issue by mrvdb** [mrWheel/DSMRlogger2HTTP#13]
While outputting info to Serial and TelnetStream, the Telegramcounter is increased twice.

Here's the patch that is needed:
https://github.com/mrvdb/DSMRlogger2HTTP/commit/2c9352743f8db4cfd1bb4f372b6093246f5103ce

If you like I can make a pull request

**Comment by mrWheel** [comment]
Already fixed

**Comment by mrvdb** [comment]
Nice.  Am I looking in the wrong place or just being impatient, as the file on master doesn't have that change yet?

**Comment by mrWheel** [comment]
@mrvdb 
Marcel, I'm going to Archive this repository.
There is a total redesign of the firmware that you can find [here](https://github.com/mrWheel/DSMRloggerWS) that does not have this error...

For your situation it is best to alter the lines in your own copy or ... switch to the `DSMRloggerWS` firmware

**Comment by mrvdb** [comment]
@mrWheel Thanks, I've indeed already made changes in my local setup. The new firmware looks interesting!
