### ISSUE TITLE
Geen gasstanden

### ISSUE THREAD

**Issue by jicho** [mrWheel/DSMRlogger2HTTP#2]
Hi,

Wat kan er aan de hand zijn als ik geen gasmetingen binnen krijg? Stroom werkt als een trein, gas metingen blijven op 0 staan... De slimme meter geeft wel de gas stand door en m'n vorige aansluiting i.c.m. een USB kabel met een RasPi gaf ook netjes gasmetingen door...

Dit is wat getActual.json retour geeft:

```
{  
   "Timestamp":"181202135402W",
   "Energy_Delivered":"1346.791",
   "Energy_Returned":"0.000",
   "Gas_Delivered":"0.00",
   "Energy_Delivered_Tariff1":"616.279",
   "Energy_Delivered_Tariff2":"730.512",
   "Energy_Returned_Tariff1":"0.000",
   "Energy_Returned_Tariff2":"0.000",
   "Power_Delivered":"0.119",
   "Power_Returned":"0.000",
   "Voltage_l1":"228.5",
   "Current_l1":"0",
   "Voltage_l2":"0.0",
   "Current_l2":"0",
   "Voltage_l3":"0.0",
   "Current_l3":"0",
   "Power_Delivered_l1":"119",
   "Power_Returned_l1":"0",
   "Power_Delivered_l2":"0",
   "Power_Returned_l2":"0",
   "Power_Delivered_l3":"0",
   "Power_Returned_l3":"0"
}
```

Mocht het handig zijn mijn device aldus device info:
ISK5\2M550E-1012

P1 version aldus device info:
50

Gebruikte firmware:
v0.7.6 (Oct 27 2018)

Gebruikte versie arduino-dsmr library:
De laatste die op de Git staat (versie van gisteren)

Mijn kennis is te beperkt om de boel te debuggen, mocht iets na moeten kijken, dan wil ik dat met alle liefde doen :)

Aanvulling:
Bij equipment ID staat momenteel onder device info "unknown". Beetje vreemd als je het mij vraagt...

**Comment by jicho** [comment]
Oh jee, de software zit nog uitgebreider in elkaar dan ik al dacht! Je kunt via Telnet (en wat geduld) een telegram afvangen. 't Is me gelukt om een telegram af te vangen:

```
/ISK5\2M550E-1012                                                               
                                                                                
1-3:0.2.8(50)                                                                   
0-0:1.0.0(181202172628W)                                                        
0-0:96.1.1(453030*************************323137)                                  
1-0:1.8.1(000616.846*kWh)                                                       
1-0:1.8.2(000730.512*kWh)                                                       
1-0:2.8.1(000000.000*kWh)                                                       
1-0:2.8.2(000000.000*kWh)                                                       
0-0:96.14.0(0001)                                                               
1-0:1.7.0(00.089*kW)                                                            
1-0:2.7.0(00.000*kW)                                                            
0-0:96.7.21(00009)                                                              
0-0:96.7.9(00004)                                                               
1-0:99.97.0(2)(0-0:96.7.19)(180116115413W)(0000002996*s)(181103104217W)(00000042
71*s)                                                                           
1-0:32.32.0(00009)                                                              
1-0:32.36.0(00001)                                                              
0-0:96.13.0()                                                                   
1-0:32.7.0(225.4*V)                                                             
1-0:31.7.0(000*A)                                                               
1-0:21.7.0(00.089*kW)                                                           
1-0:22.7.0(00.000*kW)                                                           
0-2:24.1.0(003)                                                                 
0-2:96.1.0(4730303********************333137)                                  
0-2:24.2.1(181202172503W)(00282.873*m3)                                         
!0D03     
```

'k Kan me vergissen, maar volgens mij is er een gasmeterstand beschikbaar en ook is er een equipment ID beschikbaar. Zou dus, voor mijn gevoel, niet op "unknown" moeten staan.

**Comment by mrWheel** [comment]
Ik zou zeggen dat dit:

```
0-2:96.1.0(4730303********************333137)                                  
0-2:24.2.1(181202172503W)(00282.873*m3) 

```
De gas info is. Mijn meter is ook 5.0 maar wellicht dat jouw gas-meter andere info stuurt ...

De dsmr library parsed:

```
"0-1:96.1.0(0000000000000000000000000000000000)\r\n"
"0-1:24.2.1(150117180000W)(00473.789*m3)\r\n"

```
Ik denk dat je de bibliotheek moet aanpassen (of contact opnemen met Matthijs Kooijman!

**Comment by jicho** [comment]
Thanks, 'k ga kijken wat Matthijs Kooijman zijn reactie is (https://github.com/matthijskooijman/arduino-dsmr/issues/19).

Als ik mijn versie vergelijk met het voorbeeld hierboven, dan lijkt het er op dat het probleem zit in het beginnende gedeelte (0-2) in mijn telegram t.o.v. van de 0-1 in het voorbeeld.

Maar goed, laten we maar even wachten op de expert.

**Comment by jicho** [comment]
Het probleem zit hem in het feit dat mijn gasmeter (is vervangen) nu op MBUS 2 zit i.p.v. 1. De paarse library gaat er vanuit dat de gasmeter op MBUS 1 aanwezig is...

Ik kom dus niet om een handmatige aanpassing van de library heen :(

**Comment by jicho** [comment]
Kleine aanvulling voor iemand anders die dit leest en hetzelfde probleem heeft...

Het aanpassen de ID's in deze twee constanten in de arduino-dsmr library:
```
const uint8_t GAS_MBUS_ID = 1;
const uint8_t WATER_MBUS_ID = 2;
```

is de oplossing. 'k Heb gasmetingen :)
