### ISSUE TITLE
Metingen afgelopen 4 uur

### ISSUE THREAD

**Issue by jicho** [mrWheel/DSMRlogger2HTTP#3]
Hi,

Waarom zijn is het totaal van de afgelopen 24 uur in kWh en is het energie verbruik in de tijdseenheden erboven in Wh?

Is dan niet een beetje lastig? Je moet nu dubbel kijken om het overzicht goed te kunnen interpreteren.

**Comment by mrWheel** [comment]
In een korte periode verbruik je niet zoveel energie. Vandaar de kleinere eenheid.
