### ISSUE TITLE
Eerste stroomverbruik registratie doet iets vreemds

### ISSUE THREAD

**Issue by jicho** [mrWheel/DSMRlogger2HTTP#4]
Hi,

Gisteren heb ik de logger in gebruik genomen i.c.m. het bordje van Opencircuit. Werkt goed, alleen de eerste registratie is een beetje (denk ik) vreemd.

In het "verbruik van afgelopen week"  krijg ik op zaterdag niet het dagtotaal van de zaterdag te zien, maar het totaal van T1 + T2 vanaf het moment dat de meter actief is. Zou de logica niet zo moeten werken dat als voor het eerst gaat meten je geen totalen toont tot dus toe?

Of... heb ik tijdens de installatie van de software iets over het hoofd gezien? :)

**Comment by mrWheel** [comment]
Nee, helemaal volgens design. Wat wordt opgeslagen is de meterstand. Om het verbruik in een periode te bepalen wordt de vorige meterstand van de daarná gemeten stand afgetrokken. Als de eerste stand "0" is ... krijg je een vreemde waarde die uiteindelijk uit het overzicht wegloopt.
Als je daar niet op kunt wachten kan je de tabel via de maintenance page downloaden, aanpassen en weer uploaden (dan wel via telnet meteen op "G" klikken om de bestanden in het geheugen te laden!
