### ISSUE TITLE
Call of overloaded 'String(IPAddress)' is ambiguous

### ISSUE THREAD

**Issue by softstones** [mrWheel/DSMRlogger2HTTP#6]
Arduino IDE v1.8.8 geeft een error tijdens het compileren (Call of overloaded 'String(IPAddress)' is ambiguous). Het betreft regel 21 in de sketch 'WiFi Stuff'. Het commenten van de betreffende regel zorgde ervoor dat de ESP8266 geen verbinding maakte met het netwerk.

Direct de .bin flashen met esptool werkte wel.

**Comment by mrWheel** [comment]
@softstones 
Ik heb een nieuwe versie (v0.7.7) ge-upload die geschikt is voor de Arduino IDE 1.8.8 én ESP8266 core versie 2.5.0
