### ISSUE TITLE
Buildin led must "2" for ESP-01S

### ISSUE THREAD

**Issue by DannyvdSluijs** [mrWheel/DSMRlogger2HTTP#7]
The ESP-01S board that is provided by OpenCircuit as a replacement will not work with the current settings. After some tinkering I found when configuring the building led to `2` it works without the need to change anything.

I believe it would be wise to add this detail to the read-me as well.

**Comment by dingetje** [comment]
@DannyvdSluijs thanks!

**Comment by mrWheel** [comment]
@DannyvdSluijs thanks indeed! And I will.
